In [16]:
#Import glob package and read the desired files, making them into their own dataframe, with a sample of the data to comfirm that it worked.
import glob
data_files = glob.glob('s??/s??.txt')
df_list = [pd.read_csv(d, sep="\t") for d in data_files]
df = pd.concat(df_list)
df.sample(8)

,id,year,month,day,hour,minute,gender,age,handedness,wait,block,trial,target_location,target,flankers,rt,response,error,pre_target_response,ITI_response,target_on_error
168,3,2015,5,28,14,9,f,50,r,6.539,5,9,up,black,neutral,0.377,white,False,False,False,0.024
128,2,2015,5,25,14,36,f,21,r,2.156,4,1,right,black,neutral,0.442,black,True,False,False,0.024
110,1,2015,5,22,11,30,m,25,r,1.392,3,15,down,white,congruent,0.378,white,True,False,False,0.024
112,2,2015,5,25,14,36,f,21,r,12.508,3,17,right,white,incongruent,0.475,black,False,False,False,0.024
132,3,2015,5,28,14,9,f,50,r,1.631,4,5,down,black,incongruent,0.501,black,True,False,False,0.023
70,3,2015,5,28,14,9,f,50,r,3.511,2,7,left,white,incongruent,0.586,white,True,False,False,0.023
25,1,2015,5,22,11,30,m,25,r,3.240,practice,26,up,white,congruent,0.425,white,True,False,False,0.023
36,3,2015,5,28,14,9,f,50,r,2.684,1,5,right,black,neutral,0.436,black,True,False,False,0.024

In [28]:
# Converting data from seconds to miliseconds.
df = df.assign(rt_ms=df['rt']*1000)

In [46]:
# Making a sub dataframe with only the desired data,
df.groupby('flankers').count()

,id,year,month,day,hour,minute,gender,age,handedness,wait,block,trial,target_location,target,rt,response,error,pre_target_response,ITI_response,target_on_error,rt_ms,log_rt,rt_inv
flankers,,,,,,,,,,,,,,,,,,,,,,,
congruent,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
incongruent,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
neutral,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240

In [48]:
# Cleaning the new sub dataframe and getting rid of the undesired condition.
df = df[df.flankers != 'neutral']
df

,id,year,month,day,hour,minute,gender,age,handedness,wait,block,trial,target_location,target,flankers,rt,response,error,pre_target_response,ITI_response,target_on_error,rt_ms,log_rt,rt_inv
32,3,2015,5,28,14,9,f,50,r,2.684,1,1,down,white,incongruent,0.480,white,True,False,False,0.023,480.0,6.173786,2.083333
33,3,2015,5,28,14,9,f,50,r,2.684,1,2,left,black,incongruent,0.481,white,False,False,False,0.024,481.0,6.175867,2.079002
37,3,2015,5,28,14,9,f,50,r,2.684,1,6,up,black,incongruent,0.483,black,True,False,False,0.022,483.0,6.180017,2.070393
38,3,2015,5,28,14,9,f,50,r,2.684,1,7,right,white,congruent,0.390,white,True,False,False,0.023,390.0,5.966147,2.564103
43,3,2015,5,28,14,9,f,50,r,2.684,1,12,left,white,incongruent,0.538,white,True,False,False,0.023,538.0,6.287859,1.858736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,2,2015,5,25,14,36,f,21,r,3.096,5,21,down,white,incongruent,0.836,white,True,False,False,0.024,836.0,6.728629,1.196172
186,2,2015,5,25,14,36,f,21,r,3.096,5,27,down,white,congruent,0.416,white,True,False,False,0.024,416.0,6.030685,2.403846
187,2,2015,5,25,14,36,f,21,r,3.096,5,28,left,white,congruent,0.416,white,True,False,False,0.024,416.0,6.030685,2.403846
188,2,2015,5,25,14,36,f,21,r,3.096,5,29,right,white,congruent,0.408,white,True,False,False,0.024,408.0,6.011267,2.450980
189,2,2015,5,25,14,36,f,21,r,3.096,5,30,up,black,incongruent,0.644,black,True,False,False,0.024,644.0,6.467699,1.552795